name: Deploy Tailwind CSS
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    # DOCKER TAILWIND - NO NPM PROBLEMS
    - name: Build Tailwind CSS
      uses: docker://ghcr.io/tailwindlabs/tailwindcss:latest
      with:
        args: "-i ./src/input.css -o ./dist/output.css --minify"
    
    - name: Setup dist folder
      run: |
        mkdir -p dist
        cp src/index.html dist/
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
